### ISSUE TITLE
Document new shortcodes in the README

### ISSUE THREAD

**Issue by robyngit** [OHI-Science/OHI-website#118]
The README describes each of the custom shortcodes that can be used in markdown, so that content editors know that they exist and how to use them. Some still need documentation:

- [x] peopleCards
- [x] ~~buttons~~ *(deleted in favour of using the 'button' shortcode multiple times)*
- [x] news
- [x] contributors
- [x] newsHead

**Comment by ThomasThelen** [comment]
Fixed in #136
