### ISSUE TITLE
Website Review Comments

### ISSUE THREAD

**Issue by Melsteroni** [OHI-Science/OHI-website#125]
I have had a chance to review the draft website and here are my comments.

Thanks!!

### Launch page

Currently, some of the buttons aren’t going anywhere.

“Global Scores” button - >  Should link to the “GLOBAL SCORES” tab (the one with the global map of scores)

“OHI+ Assessments” Button.  Can we change the name to “Learn More” and link to this page:
http://probable-cattle.nceas.ucsb.edu/ohi+/

“Conduct an assessment” Button links to this page:
http://probable-cattle.nceas.ucsb.edu/ohi+/conduct/ 

### Right column directory throughout website

These seem like they should be consistent.  But they change depending on where you are.

For example: if I select GLOBAL SCORES  -> Scores by Country
the right column directory includes: Goals and Data Download

If I select GLOBAL SCORES  -> Scores by Goal
the right column directory includes: Scores, Goals, and Data Download

(it would also be more consistent if the names were the same on the right hand side, so:
Scores by Country
Scores by Goal
Data Download

For METHODOLOGY -> Methods Overview it includes:
Pressure Descriptions
Resilience Descriptions
Deep Dive

for METHODOLOGY -> goals, nothing shows up on the right..
etc.

### OHI + TAB
1.	Once the map is made that describes OHI+ regions, can we also include it on the OHI+/WHAT IS OHI+ page?  I think this will involve making a special shortcode for it?
2.	for the OHI+/OHI ASSESSMENTS: On the list of regions, I think a bit more demarcation between the major global regions (e.g., Africa, Arctic, etc.) would look good. As it is, the list all kind of runs together.
3.	For the OHI+/Conduct and OHI+: Is it possible to have the circle figure (a static version) and process description at the top of the page? See Issue #75

### ABOUT/NEWS

Is it possible to make the 2nd part of the post more distinct from the post title?
For example:
2020 GLOBAL OCEAN HEALTH INDEX and 
2020 GLOBAL OCEAN HEALTH INDEX SCORES NOW AVAILABLE!

Are about the same size and color. Maybe the 2nd title needs to be smaller?
Also, is it possible to separate the posts more?  Maybe include a snippet of the text…something?

### ABOUT/CONTACT OHI
We can eliminate the PRESS RESOURCES section.

**Comment by ThomasThelen** [comment]
Awesome feedback!


### About/News

In this section, I made the second title smaller than the top, moved the data closer to the top title, and increased the space between posts. If there's time, I'll all some news text to the 'read more' text.


<img width="1680" alt="Screen Shot 2021-10-11 at 11 31 24 AM" src="https://user-images.githubusercontent.com/9289652/136837777-0dc0a800-4439-4d1b-88d1-f6ebc1c7c282.png">

**Comment by ThomasThelen** [comment]
### OHI + TAB

Right now I think those two visualizations are nice-to-have's-if we get to them we should be able to do these. For the assessments page I increased the font size of the continent to make it stand out more/to make it more clear when scrolling and reaching a new continent. If there's anything else there that might help I should be able to get it in!

<img width="1680" alt="Screen Shot 2021-10-11 at 11 35 11 AM" src="https://user-images.githubusercontent.com/9289652/136838478-c806590a-6b16-49df-b435-2054fe6272ae.png">

**Comment by ThomasThelen** [comment]
### Launch page

Fixed in f5b9346384fa7bfca05bfe95c0c5cafc29f676cd. Good catch!

**Comment by robyngit** [comment]
> The GOALS card (but not the other cards) has extra annotation that doesn't quite make sense.

I call dibs on fixing this one @ThomasThelen

**Comment by ThomasThelen** [comment]
@Melsteroni Would this work for the top of the assessments page?

The first image is zoomed out so you can see the overall layout. The second image is real size.

<img width="788" alt="Screen Shot 2021-10-14 at 7 02 16 PM" src="https://user-images.githubusercontent.com/9289652/137420623-405b7806-94a7-4475-a04c-6e2f3cb82dcd.png">

~~~
~~~
~~~
~~~

<img width="1680" alt="Screen Shot 2021-10-14 at 7 02 30 PM" src="https://user-images.githubusercontent.com/9289652/137420643-49c61bb4-6e79-4a69-9086-d2259ec1b6f6.png">

**Comment by ThomasThelen** [comment]
The news section look much better with preview text...

<img width="1678" alt="Screen Shot 2021-10-14 at 7 21 53 PM" src="https://user-images.githubusercontent.com/9289652/137422191-edbbb676-68cb-4f9e-97b5-c38d737ef204.png">

**Comment by ThomasThelen** [comment]
I think we were able to accomplish _most_ of these. The only thing that I see remaining that we weren't able to get to is the map on the assessments page (tracked in issue #21). If that looks to be the case I think this issue should be closed.

**Comment by Melsteroni** [comment]
We can save the map for another year!
