### ISSUE TITLE
Deployment Issues

### ISSUE THREAD

**Issue by ThomasThelen** [OHI-Science/OHI-website#130]
When deploying the built website, it looks like the styles aren't being loaded and there's an `Uncaught SyntaxError: Unexpected token '<'` in the console

<img width="1680" alt="Screen Shot 2021-10-15 at 10 09 09 AM" src="https://user-images.githubusercontent.com/9289652/137526432-bcd9a0f6-5e8f-4ec8-9c03-60db12f45c83.png">

**Comment by robyngit** [comment]
@ThomasThelen What do you have the baseURL set to? Looks like it might be set to `probable-cattle.nceas.ucsb.edu` - I think it needs the `http://`?
