### ISSUE TITLE
All checks have failed

### ISSUE THREAD

**Issue by Melsteroni** [OHI-Science/OHI-website#131]
@ThomasThelen 
I think something went wrong somewhere because it seems that the last several commits have not resulted in a successful website build.

I think it is making it so subsequent commits result in an "All checks have failed" error (even a simple test one that I did that should not have failed).

**Comment by ThomasThelen** [comment]
Forgot to switch one last reference over to the main branch. It should be rendering now, https://ohi-science.org/OHI-website/goals/artisanal-fishing-opportunities/
