### ISSUE TITLE
Help: How do I render the website locally with Hugo?

### ISSUE THREAD

**Issue by Melsteroni** [OHI-Science/OHI-website#133]
I managed to install brew and hugo (adding this here for my future reference: https://www.youtube.com/watch?v=WvhCGlLcrF8).

So, now: what do I do to view the website?

I tried using my terminal to navigate to the OHI-website directory on my computer.  and typed "hugo server"

It seemed to work, but it threw some errors.  I'm wondering if I need extra packages or something?

Or, maybe there is a better way to do this?

![image](https://user-images.githubusercontent.com/5685517/138358778-79dc81f4-df86-4663-bca1-4341a66a51f5.png)

Thanks!!

**Comment by ThomasThelen** [comment]
It looks like some of the packages might be missing. I would try running `npm install` from the `OHI-website/` root directory and then try `hugo server` again.
