### ISSUE TITLE
Use the colour variables defined in _variables.scss

### ISSUE THREAD

**Issue by robyngit** [OHI-Science/OHI-website#29]
The `_variables.scss` file defines colours that are commonly used throughout the site. However, some `.scss` files (especially under `/partials/`) use the hard-coded hex colour code instead of the variable.

It's better to use variables rather than the colour hex-codes where possible (makes it easier if we want to change the colours one day.)

**Comment by ThomasThelen** [comment]
A took a stab at this in 217e4edb43ec74f117cf10228aa657a3ef2fcc7f . Note that some thing weren't changed. For example [gradients](https://github.com/OHI-Science/OHI-website/blob/main/assets/scss/partials/page-header.scss#L52)

I went though all of the files _except_ the ones in `data-viz`. I'm not sure if you want me mucking around in those styles, but I definitely wouldn't mind

**Comment by robyngit** [comment]
More progress made on this issue in #126, though there are still hex codes that should be switched to variables, and color variables that could probably be combined. Since everything works and looks good though, I think this issue should go on the back burner to be fixed if needed in the future.

**Comment by ThomasThelen** [comment]
Fixed in #136
