### ISSUE TITLE
Tooltips for countries with scores sometimes show NA

### ISSUE THREAD

**Issue by robyngit** [OHI-Science/OHI-website#44]
In the scores globe, select the goal "Marticulture". Then hover over one of the dark red regions (e.g. Argentina). The tooltip shows the score as "NA" even though the region shading doesn't show a missing value (it would be grey):

<img width="530" alt="Screen Shot 2021-06-23 at 18 39 50" src="https://user-images.githubusercontent.com/26600641/123177027-7e853d00-d452-11eb-86e5-21f8ed3f2c9c.png">

Either the score value is actually NA and the region shading is inaccurate, or there is a low score and the tooltip is failing to show it.

**Comment by Melsteroni** [comment]
Happening with zero values.
![image](https://user-images.githubusercontent.com/5685517/129362267-ff02678d-fb99-47f5-8bcb-69d7a68ce5fd.png)
