### ISSUE TITLE
Show trends for each region on the scores globe

### ISSUE THREAD

**Issue by robyngit** [OHI-Science/OHI-website#45]
Add a toggle for the scores globe that switches between scores over the 10 year period (what's currently shown) and trends for each region.

- [x] To implement this, we first need trends data from @Melsteroni.  Ideally, this CSV should use the same headers, country codes, and goal codes as the [scores CSV](https://github.com/OHI-Science/OHI-website/blob/data_viz/content/data/scores.csv)

**Comment by robyngit** [comment]
The trends data is available [here](https://github.com/OHI-Science/ohi-global/blob/draft/yearly_results/global2020/Results/data/trends_website.csv)

Related issue: https://github.com/OHI-Science/OHI-website/issues/71

**Comment by Melsteroni** [comment]
I will update this csv to be the same as the scores csv.  Two complications: 

1. "scenario" doesn't really apply because the trend collapses the data across all years. For consistency, I will keep the variable and just use the current year?
2. "dimension": I can write something like "average_change".  This doesn't really match any of the dimensions from the scores.

Let me know if you need something different from this.

**Comment by Melsteroni** [comment]
I have updated the trends_website.csv to be more similar to the scores.  Let me know if I need to make additional changes.

Attached here.  And located here: https://github.com/OHI-Science/ohi-global/blob/draft/yearly_results/global2020/Results/data/trends_website.csv
[trends_website.csv](https://github.com/OHI-Science/OHI-website/files/6983675/trends_website.csv)

**Comment by robyngit** [comment]
Thank you!

**Comment by robyngit** [comment]
Here's how the map looks with the trends data. We may want to change the color scale:

<img width="1542" alt="Screen Shot 2021-09-22 at 17 40 38" src="https://user-images.githubusercontent.com/26600641/134425827-6c9bef99-64b3-4164-a2b7-17c6f67aafd0.png">

**Comment by Melsteroni** [comment]
ooohhh nice!  I can send you the color scale we use (not that we are tied
to it).  How is it best to send that? (e.g., vector of hexidecimal colors,
etc)

**Comment by robyngit** [comment]
vector of hexidecimal colors would work well, thanks!
