### ISSUE TITLE
ABOUT tab layout

### ISSUE THREAD

**Issue by Melsteroni** [OHI-Science/OHI-website#65]
I am also adding this information to here: https://docs.google.com/document/d/1MG82oW9zNIVRmJUYn8ZSaFkvJZCfI-WDSWQKiH0B_Bk/edit#heading=h.p7tr3ka8rju2

The tab in the original website: 
![image](https://user-images.githubusercontent.com/5685517/125960991-d5c96c6c-3852-4fd3-ba55-6e297c851802.png)

The current draft:
![image](https://user-images.githubusercontent.com/5685517/125961385-4a716707-ba94-47ff-abab-752b9d190b1c.png)

## For the "TEAM" page:

Change from TEAM to PEOPLE

Break into 2 sections:
1.  Current team using this format from oceanhealthindex.org: 
![image](https://user-images.githubusercontent.com/5685517/125962869-fe3a845d-c73c-4bf0-b64d-3286bf2ee0c5.png)

But, remove Julia.  Change my title to "Senior Scientist".  Add Gage (@gclawson1: do you have a picture to add?), with title: Lead Analyst

2. Then a section for previous contributors.  This will include the people from this page: http://www.oceanhealthindex.org/about/contributors
but with 2019 people merged in with the rest.  

For the Science section, we will also need to add: Eva Schemmel, Ning Jiang,  Ellie 
Campbell, Iwen Su, Camila Vargas, Madeline Berger, Laura Ingulsrud, Sara Orofino, Molly Williams 

and Communication, we need to add: Erin O’Reilly

So: 
Previous Contributors
We gratefully acknowledge the following people and organizations for their important contributions to the Ocean Health Index project.

I like the idea of continuing to group contributions by the categories: Science, Advisory, Media, Communications and Outreach, etc.

## For the "SUPPORTERS" page: 
the text (and I think the relevant icons should also be used):

We are grateful for the generous support from the Pacific Life Foundation and the Gordon and Betty Moore Foundation, as well as our founding contributors for helping us build the Ocean Health Index from the beginning.  Without their generosity of intellectual and financial support the Ocean Health Index would not be a reality.

The Pacific Life Foundation made a commitment in 2011 to become the Founding Presenting Sponsor of the Ocean Health Index.  The Foundation has a strong tradition of creating positive societal change through its grant making program. Established in 1984 and headquartered in Newport Beach, CA, the Pacific Life Foundation is the charitable giving arm of Pacific Life Insurance Company and, during that time, has contributed over $84 million in donations to thousands of nonprofits.

The Gordon and Betty Moore Foundation enables lasting, meaningful change through sustained, scientifically sound philanthropy, seeking to achieve through philanthropy what Gordon Moore accomplished for the world of computing: to create an ever more powerful engine of progress in society.

The World Ocean Observatory is a major utility for ocean communication as a means to advance public awareness and political will, dedicated to providing information and education about the health of the ocean. Online at worldoceanobservatory.org.

Beau and Heather Wrigley generously provided the founding grant to the Ocean Health Index. Mr. and Mrs. Wrigley brought together the best in business thinking and marine conservation; they were early originators of the Ocean Health Index concept and nurtured its development through their leadership of the Ocean Health Council. 

Since 2007, Mr. and Mrs. Wrigley have provided vision, support and leadership to this project. Mr. Wrigley is a Board member at Conservation International, co-chair of CI’s Ocean Health Council, the former Chairman and CEO of the William Wrigley, Jr. Company, and an avid SCUBA-diver.

FOUNDING DONORS
Darden Restaurants Foundation

Akiko Shiraki Dynner Fund for Ocean Exploration and Conservation

Mr. Jonathan Kaplan and Ms. Marci Glazer

Thomas W. Haas Fund of the New Hampshire Charitable Foundation

Jayne and Hans Hufschmid

Management 360

Oak Foundation

Dan Sten Olsson

Ms. Carol L. Realini

Joseph S. and Diane H. Steinberg Charitable Trust

## For the "CONTACT" page: 
I think this can be simplified to link to Gage's email.  He can take care of simple inquiries and forward the more complex ones to Ben or me. I'm not sure how this works, but should we use an email address that sends to Gage's email but looks different?  I don't think we need to "press kit" or "logo" buttons. 

There isn't a newsletter, so we can drop all that. But: is it worth having people sign up to get our blogposts when we post them?

**Comment by ThomasThelen** [comment]
We can certainly create a new email address and forward it to Gage. I think to create a new email with the OHI domain we'd want to wait until the domain is transferred (I'm not entirely sure how custom emails are made but it should be possible). 

Hugo doesn't support newsletters out of the box-but there should be third party solutions out there (they might not be as automatic to send when a new post is created-I'm _guessing_ that someone will have to create an email and it'll get sent to everyone on the newsletter). I don't think there's any harm in having a newsletter! I can create a new issue around that where we can discuss it, and for the time being I'll leave it out of the 'contact' page.

**Comment by ThomasThelen** [comment]
Most of this has been completed and is on the dev site; issue #100 is for the contact page.
