### ISSUE TITLE
Create a shortcode to link to page resources

### ISSUE THREAD

**Issue by robyngit** [OHI-Science/OHI-website#70]
Create a shortcode which will retrieve a particular resource by its matching filename ([example](https://www.regisphilibert.com/blog/2018/01/hugo-page-resources-and-how-to-use-them/#in-my-markdown)). This will be used to create links to download data, e.g. the `scores.csv` data from the Download Data page.

**Comment by robyngit** [comment]
@ThomasThelen I think you're working on this at the moment?

**Comment by ThomasThelen** [comment]
Ah you know I ended up just referencing the file relative to `/content`. This way, there isn't any additional processing that needs to be done. My work was done in the context of having two buttons that _link_ to content, not specifically for downloading (although if the link is a relative path, the file will download). This allows me to use the buttons on content download sections (like the contact page) and on content for linking to other pages (goal pages that don't have subgoals). Do we still need this issue?

**Comment by robyngit** [comment]
Okay! I updated the `button` shortcode so that it can also be used to link to data files or images files. I added an example in the data page. The path just needs to start with `data/` or `images/` for it to work, e.g. `{{<button text="Download data" link="data/scores.csv" >}}`
