### ISSUE TITLE
Page Content: OHI+ / OHI ASSESSMENTS

### ISSUE THREAD

**Issue by Melsteroni** [OHI-Science/OHI-website#76]
For this page:
### OHI+ / OHI ASSESSMENTS

This can basically look like this page: https://ohi-science.org/projects/ohi-assessments/

I was noticing that this set up so each region report is a blogpost, which seems like a good approach to me.  You can check out the  "blogposts" in this folder: ohi-science.github.io/_posts/assessments/

### The map
The code to make the map and the html version of the map is in the ohi-science.github.io repo as well.  I'm not sure if it would work to just grab that map (located here: https://github.com/OHI-Science/ohi-science.github.io/blob/master/_includes/themes/OHI/maps/allRegions.html)? Or, if we want to do something else.  
Regardless, we can wait on getting the map.  This isn't super high priority.

**Comment by robyngit** [comment]
Issue #21 overlaps with this one, but I'll leave both issues open as this one is more about the overall content of the OHI Assessments page, and 21 is really about the map visualization.

**Comment by ThomasThelen** [comment]
The assessment list and individual pages have been added in 34337d39031fa89fbc9525daf15b4cc381dc2f5b

I'll leave this open until #21 is done

**Comment by ThomasThelen** [comment]
Closing this issue in favor of issue #21
