### ISSUE TITLE
Rename the "top-nav" layout element

### ISSUE THREAD

**Issue by robyngit** [OHI-Science/OHI-website#94]
This name could cause some confusion as this navigation element is at the top of sections, not at the top of the page (the main navigation as at the top of the page). A better name might be "breadcrumb", which is a common name for these types of nav elements.

**Comment by ThomasThelen** [comment]
Fixed in 91a420ebfe3c51d4e3bf3b7dbe0a22d9526763f2. The top-nav elements are now 'breadcrumb' elements.
